#use node_js
language: node_js

#define node js version to use
node_js:
  - "7"

#choose branch on commit of which this script should excecute
branches:
  only:
    - master

#set notifications frequency
notifications:
  email:
    on_success: never
    on_failure : change 


before_install:
  - gem update --system
  - gem install bundler
  - bundle check || bundle install 

install:
  - npm install -g firebase-tools 

script: 
  - set -e 
  - jekyll build 

after_success:
  - firebase deploy --token "$FIREBASE_API_TOKEN" --project website-b7fa0

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer

sudo: false # route your build to the container-based infrastructure for a faster build