layout: sidebar
style: light

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:
  sort_by: pushed
  # sort_by options:
  #   - pushed
  #   - stars
  limit: 9
  exclude:
    archived: false
    forks: true
    projects:
    # - repo-name

# social_media:
  # behance: your_username
  # dribbble: your_username
  # facebook: your_username
  # hackerrank: your_username
  # instagram: daiemly
  # keybase: your_username
  # linkedin: dai-emily
  # mastodon: your_username
  # medium: your_username
  # stackoverflow: your_user_id
  # telegram: your_username
  # twitter: your_username
  # unsplash: your_username
  # vk: your_username
  # website: http://your_website_url
  # youtube: your_username

topics:
  - name: Spark AR
    web_url: https://sparkar.facebook.com/ar-studio/
    image_url: https://repository-images.githubusercontent.com/238927599/670df700-49b8-11ea-8e07-4d0c886ccc9a

  - name: Adobe After Effects
    web_url: https://www.adobe.com/ca/products/aftereffects.html
    image_url: https://seeklogo.com/images/A/after-effects-cc-logo-BCC55BAFF7-seeklogo.com.png

  - name: Adobe Photoshop
    web_url: https://www.adobe.com/ca/products/photoshop.html
    image_url: data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAOMAAADeCAMAAAD4tEcNAAAAh1BMVEUAHSYAyP8AzP8ACxAKhqoKgaMAAAAA0P8Ay/8AGSEAN0YAAAUAncgA0f8Azv8AFRwALjsAEBYACQ0Aos8ASFwAcI8AjLMAwfYAExoAWXIKg6YAkroArt4AaogAe50AT2UAt+kAJC8AYXwAqtkAKDQAP1EAos4APU4AZYEAVWwATmMAMUAAu+/xmyrpAAAHqUlEQVR4nO2d64KqKhSAvTQLzMAs85LldJmZaqb3f76jzW4ywMouqBy+f7Nzm18gwmKBhqk+RtMXIAHtqAbaUQ20oxqcHLGlFph3xOtpTyWma8w50gxslYA3yju+2YZK2NpRCbSjGmhHNdCOaqAd1UA7qoF2VAPtqAbaUQ20oxpoRzXQjmqgHdVAO6qBdlQD7agG2lENtKMaaMcbcRzPi2M/55ArMiph237svObSb+YJjuD0P993q+18kmXZdNoLC9Jfwl42WQUGwMhvzvRxR29NUA49wuRx5f+CiDlL50MYeS/TuMjDjk6fmNfBFiVRuoNRE6X5BEd0g+MBC0XhB8i3lOl40Bz04XU2YiQ75rWWpJ7/Oh8R0h3zsjRXcouyAUfTJAOpd2UjjiZdOBKfI804mjhaypNsyDGXNKRV16YcTbyQ1vA05mjSgSzJ5hxNspX0nHyFI8a/ffGig44x+2npOEl35Asco/EgH1NNs2KkFQ5mJqIVnlYqp7Y+3xEPwC3Gxr/DZRfgZzKm1BRB+lJK8hWOLnOED05miiyxnGZHguPha9xQ1DShpYyClORoGBCY/G0pJzomzdHwlxEnifcyKqs8R8P74AtSSqsj0dHwEy70QzMJlVWmowEDtiTxWEJllerofPCNq2qOgoIkwys3pON4cex53gP3rVzHOGELkiZx5dGeDXkvKdglSbILNsv8D9euProauY4GsOVIs4rBRwyw662j3xA8OhDNBm+JUT/cLttxzUha4Uh4WbAaW8hiDsaYUrIPA6hnKdlxFFo3HG2PMhNVDcqwhaL3WpKSHf0J0zfHa65hdWAi7MGX/lNUqzWW7BivWMcZe7n+x+xqZAG32dF7Z49mHd0dexd2zvH7iiPMb5rqa7XjlXJ0b1Jst2OcXGxz/PebFNvt6M9Zx3Kn3Ll1e5tWO9pTxtFKS30AWDNPz046umynnPZO3xXz48suOsKeuVo690sfXn9qtN/RGbIlhYK/bhk/KCnO9q9DXoTcu+FoZ2wnDZ2+CsZcMVp0nSWfP8N+kEx644gcI+5tduSqanmGzuY6qSh0wI6dgtjPB5PL7eC3r95iR3/F1sZSsxpzH+KAUXFiF5IxstrsCBFbUnT1N7Dnhl0oEF1GDMOUtNcRUq420tLtyAyfKydDHOh/1oruSHQUdLfx18mDvVfRrnIg7NQLYMlzhC3/hEeliBUb6nnefI8sRw9CQSemPJ4H5jzoYbcjchxj+N4Lwhd0UgrKcY7BszJ4Xu/o+HmDPyOibtpZWAbY3nrvQp+wFi+ZK//bhXAEAMPjg5sDzcuxVe7BYj3rhnxBzsMi7E3fsix7e+ul40V1ygMTAoAFG03du8+RfEXuyjFxhVoXU1fo+VSH+8Uea+2Np2TwNJeDRLbn31K6kiPY3D1jWqsxRxQyl8+F7A4/RGo/XpRNOVJ+chVEx1nmvObsRmscKT8FYIxSYTQHLb4fzFpuxhGJ+tvORhzOwWT9+ZBlM/nkmbApEQQCjpbjzQOWDThS81vcWjo/lafC5Gt4dxPbxPqOygnvUVZ9LozCe5tYyY6YzD4vlAfMLgSRad7E3lVhpTpaZPZ++TJ9Pt+sBFov7ylKeY4WMtPNtWedI0iqK4HxPUt8pDhiXKwMTG5ZGegZ+4tzHuSO3OXX9MnxEasIc9PFYNKH0W2pNc5offFHo7Pao5GXjK3SwXi8zvkapNNJ0gdw66zUhalwQP33Cy7smpIvGSMXWeQH3JHt188CgyC6lNdh1V39Inne6jY86FWm55jizu4lWumYF+XP+kKFRW+1vqKljoYD74vqskSbOjdAWx2LCptUWvKZS5dor2MRlU32Fc8RsquR5Nlmx8KyInVOkGZXTbsd8+uzU+HImXzcfke23bHqaVmZ2yug/Y554zPg78o6Cwo64JgXZcbX1xoprJ1wNGDCSRKl6moBcHHJGt2AjjjyAWZ0e055Vxz5rI9EOcd4yzxAqHqO3o5xvJD2wdIiRxCuZvkHV44o6GCbAzSE6ucBdz+S5c1nbo/jiNBoW2nJZQvUSCdrj6Obnwftt+IAJYRX175U0y5HE6Oo1webaU48mHIJk+K1aEJa5lhcPVn03ouljr7nFQs8fRd2/OqkGo/HFjoeVsbRxeBtngSfmyCZpJEo5NHJMbJ7dh58SiQXxXTOlkxco62OVyA/NQJz3XS0am1m0lHHWht+ddKRzGvtDtFFx7q7fXXQkdYKkhtddKyt2CLH0W2OpP7+UO1xhEtTjkcsOm9DPsC9jnEi7LOdnZqMl3fst9MeRyOG+YJUJWYXZUjWwV1JSE/Yn5ygM0idruQ5PvR7uaZgg4Ai+aX3c2cm6+OOjjM855HdmxwbjFVYbLdy3Or8sL95NM42UDed449n7KXvnHPnlfwR2wD2Jpln02LD+ulkGzhwv6DR3nciOF7x8oHf9w00nmvdAbSjGmhHNdCOaqAd1UA7qoF2VAPtqAbaUQ20oxpoRzXQjmqgHdVAO6qBdlQD7agG2lENtKMaaEc10I5qoB3VQDuqgXZUA+2oBtpRDbSjGmhHNRA6Zqc3N6gACBzxetpTienpbUSnFxNiSy1Oa5tufflil9GOaqAd1UA7qsH/wfE/AZHFvYvd5cUAAAAASUVORK5CYII=
  
    - name: Spark AR
    web_url: https://sparkar.facebook.com/ar-studio/
    image_url: https://repository-images.githubusercontent.com/238927599/670df700-49b8-11ea-8e07-4d0c886ccc9a
  
