layout: stacked
style: light

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:
  sort_by: pushed
  # sort_by options:
  #   - pushed
  #   - stars
  limit: 9
  exclude:
    archived: false
    forks: true
    projects:
    # - repo-name

# social_media:
  # behance: your_username
  # dribbble: your_username
  #facebook: your_username
  # hackerrank: your_username
  #instagram: your_username
  # keybase: your_username
  linkedin: gauravsinha7
  # mastodon: your_username
  # medium: your_username
  # stackoverflow: your_user_id
  telegram: gauravsinha7
  twitter: gaurav_sinha7
  # unsplash: your_username
  # vk: your_username
   website: https://gauravsinha7.github.io/
  # youtube: your_username

topics:
  - name: Machine Learning
    web_url: https://github.com/topics/machine-learning
    image_url: https://raw.githubusercontent.com/github/explore/6c6508f34230f0ac0d49e847a326429eefbfc030/topics/css/css.png
