layout: sidebar
style: light

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:
  sort_by: pushed
  # sort_by options:
  #   - pushed
  #   - stars
  limit: 0
  exclude:
    forks: true
    projects:
    # - repo-name

social_media:
  # behance: your_username
  # dribbble: your_username
  facebook: jonathan.lane
  # linkedin: your_username
  # medium: @your_username
  # stackoverflow: your_user_id
  # telegram: your_username
  twitter: majesticjondi
  # youtube: your_username
  # vk: your_username

topics:
  - name: Resumé
    description: Education, work history, skills and languages. Pretty much what you'd expect to find on a resumé!
    web_url: /resume/
    image_url:
    octicon: person

  - name: Recent Projects
    description: An outline of projects I developed and an in-depth case study of some of the solutions produced.
    web_url: /projects/
    image_url:
    octicon: project
