layout: sidebar
style: dark

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:
  sort_by: pushed
  # sort_by options:
  #   - pushed
  #   - stars
  limit: 9
  exclude:
    archived: false
    forks: true
    projects:
    # - repo-name

social_media:
  facebook: WorthingtonBaptistChurch
  ##youtube: your_username

contact:
    address: 327 East Ross Street 
    city: Worthington
    state: PA
    zipCode: 16262
    phone: (724) 297-3360

services:
  - name: Sunday School
    time: 9:45 am
    description: Sunday school for children and adults
    octicon: dashboard

  - name: Sunday Morning
    time: 10:45 am
    octicon: book

  - name: Sunday Evening
    time: 6:00 pm
    octicon: search

  - name: Wednesday Prayer Meeting
    time: 7:00 pm
    octicon: organization

