layout: sidebar
style: dark

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:
  sort_by: pushed
  # sort_by options:
  #   - pushed
  #   - stars
  limit: 9
  exclude:
    archived: false
    forks: true
    projects:
    # - repo-name

# social_media:
  # behance: your_username
  # dribbble: your_username
  # facebook: your_username
  # hackerrank: Pop Sauce
  # instagram: your_username
  # keybase: your_username
  # linkedin: your_username
  # mastodon: your_username
  # medium: your_username
  # stackoverflow: your_user_id
  # telegram: your_username
  # twitter: your_username
  # unsplash: your_username
  # vk: your_username
  # website: http://your_website_url
  # youtube: your_username

topics:
  - name: Source Code of the Universe
    web_url: http://theunapologists.com/a-beginners-guide-to-quantum-mechanics
    image_url: https://www.outerplaces.com/images/user_upload/lhc.gif
   
  - name: Random Stuff
    web_url: https://libraryofbabel.info/
    image_url: https://raw.githubusercontent.com/popsauce/popsauce.github.io/master/bis.jpg

  - name: CSS
    web_url: https://github.com/topics/css
    image_url: https://raw.githubusercontent.com/github/explore/6c6508f34230f0ac0d49e847a326429eefbfc030/topics/css/css.png

  - name: Web design

  - name: Sass
    web_url: https://github.com/topics/sass
    image_url: https://raw.githubusercontent.com/github/explore/6c6508f34230f0ac0d49e847a326429eefbfc030/topics/sass/sass.png

theme: jekyll-theme-slate
