layout: sidebar
style: light

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:
  sort_by: pushed
  # sort_by options:
  #   - pushed
  #   - stars
  limit: 9
  exclude:
    forks: true
    projects:
    # - repo-name

social_media:
  # behance: your_username
  # dribbble: your_username
  # facebook: your_username
  # hackerrank: your_username
  # instagram: your_username
  # keybase: your_username
  linkedin: ash-ma1989
  # medium: your_username
  # stackoverflow: your_user_id
  # telegram: your_username
  # twitter: your_username
  # unsplash: your_username
  # vk: your_username
  website: https://www.ashma.info
  # youtube: your_username
  WeChat: mashoushan

topics:

  - name: 我在boss直聘
    web_url: https://www.zhipin.com/gongsir/5ba2ae5248837b0d1n192Nq0FQ~~.html?ka=company-jobs/?from=ash
    image_url: https://is5-ssl.mzstatic.com/image/thumb/Purple113/v4/9f/fd/1f/9ffd1f23-358c-3cfd-fad6-71e1c2180e96/AppIcon-0-1x_U007emarketing-0-0-85-220-8.png/246x0w.jpg

  - name: 我在拉勾
    web_url: https://www.lagou.com/gongsi/443505.html?from=ash
    image_url: https://www.lgstatic.com/thumbnail_300x300/i/image3/M00/2E/09/Cgq2xlqfotmANm4kAABisF5qlmM902.png

  - name: 我在脉脉
    web_url: https://maimai.cn/contact/share/card?u=nuo5zwcptsk8&_share_channel=copy_link
    image_url: https://www.phpfans.net/img/20210416/logo_60792923426c31.png

  - name: 关于PPIO
    web_url: http://ppio.cn/?from=ash
    image_url: https://www.lgstatic.com/i/image2/M01/30/7C/CgoB5lzasoaAF_kuAAKMD93XGgc713.png

  - name: 关于我
    web_url: https://www.linkedin.com/in/ash-ma1989/?from=ash
    image_url: https://ss0.bdstatic.com/-0U0bnSm1A5BphGlnYG/tam-ogel/ae60db54936bb024336e75c7c90a8578_121_121.jpg

theme: jekyll-theme-cayman
