layout: sidebar
style: dark

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:
  sort_by: stars
  # sort_by options:
  #   - pushed
  #   - stars
  limit: 9
  exclude:
    archived: false
    forks: false
    projects:
    # - repo-name

social_media:
  # behance: your_username
  discord: Geezus42
  # dribbble: your_username
  # facebook: your_username
  # hackerrank: your_username
  # instagram: your_username
  keybase: Geezus_42
  # linkedin: your_username
  mastodon: Geezus42
  # mastodon: your_username
  matrix: Geezus42
  # medium: your_username
  signal: Geezus42
  # stackoverflow: your_user_id
  telegram: Geezus42
  twitter: Geezustx
  # unsplash: your_username
  # vk: your_username
  # website: http://your_website_url
  # youtube: your_username

topics:
  - name: Linux
    web_url: https://github.com/topics/linux
    image_url: https://raw.githubusercontent.com/github/explore/6c6508f34230f0ac0d49e847a326429eefbfc030/topics/linux/linux.png
  
  - name: Command line interface
    web_url: https://github.com/topics/cli
  
  - name: Python
    web_url: https://github.com/topics/python
    image_url: https://raw.githubusercontent.com/github/explore/6c6508f34230f0ac0d49e847a326429eefbfc030/topics/python/python.png
  
  - name: Security
    web_url: https://github.com/topics/security
  
  - name: Raspberry Pi
    web_url: https://github.com/topics/raspberry-pi
    image_url: https://raw.githubusercontent.com/github/explore/6c6508f34230f0ac0d49e847a326429eefbfc030/topics/raspberry-pi/raspberry-pi.png
  
  - name: Mastodon
    web_url: https://github.com/topics/mastodon
    image_url: https://raw.githubusercontent.com/github/explore/d004ed8f8b3a409f46c89be097d6ab0ee207cea9/topics/mastodon/mastodon.png

  - name: Markdown
    web_url: https://github.com/topics/markdown
    image_url: https://raw.githubusercontent.com/github/explore/6c6508f34230f0ac0d49e847a326429eefbfc030/topics/markdown/markdown.png


