layout: sidebar
style: light

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:
  sort_by: pushed
  # sort_by options:
  #   - pushed
  #   - stars
  limit: 9
  exclude:
    forks: true
    projects:
    # - repo-name

social_media:
  # behance: your_username
  # dribbble: your_username
  # facebook: your_username
  hackerrank: jameskip
  # instagram: your_username
  # keybase: your_username
  linkedin: jameskip
  # medium: your_username
  # stackoverflow: your_user_id
  # telegram: your_username
  twitter: jkcxii
  # unsplash: your_username
  # vk: your_username
  # website: http://your_website_url
  # youtube: your_username

topics:
  - name: AWS
    web_url: https://github.com/topics/aws
    image_url: https://raw.githubusercontent.com/github/explore/9f270b9ddad21705ebd33f4602a0aec0d22cbe4e/topics/aws/aws.png

  - name: Contentful
    web_url: https://github.com/topics/contentful
    image_url: https://raw.githubusercontent.com/github/explore/9f270b9ddad21705ebd33f4602a0aec0d22cbe4e/topics/contentful/contentful.png

  - name: CSS
    web_url: https://github.com/topics/css
    image_url: https://raw.githubusercontent.com/github/explore/6c6508f34230f0ac0d49e847a326429eefbfc030/topics/css/css.png

  - name: Docker
    web_url: https://github.com/topics/docker
    image_url: https://raw.githubusercontent.com/github/explore/9f270b9ddad21705ebd33f4602a0aec0d22cbe4e/topics/docker/docker.png

  - name: Express
    web_url: https://github.com/topics/express
    image_url: https://raw.githubusercontent.com/github/explore/9f270b9ddad21705ebd33f4602a0aec0d22cbe4e/topics/express/express.png

  - name: Firebase
    web_url: https://github.com/topics/firebase
    image_url: https://raw.githubusercontent.com/github/explore/9f270b9ddad21705ebd33f4602a0aec0d22cbe4e/topics/firebase/firebase.png

  - name: Git
    web_url: https://github.com/topics/git
    image_url: https://raw.githubusercontent.com/github/explore/9f270b9ddad21705ebd33f4602a0aec0d22cbe4e/topics/git/git.png

  - name: GraphQL
    web_url: https://github.com/topics/graphql
    image_url: https://raw.githubusercontent.com/github/explore/9f270b9ddad21705ebd33f4602a0aec0d22cbe4e/topics/graphql/graphql.png

  - name: Gulp
    web_url: https://github.com/topics/gulp
    image_url: https://raw.githubusercontent.com/github/explore/9f270b9ddad21705ebd33f4602a0aec0d22cbe4e/topics/gulp/gulp.png

  - name: HTML
    web_url: https://github.com/topics/html
    image_url: https://raw.githubusercontent.com/github/explore/9f270b9ddad21705ebd33f4602a0aec0d22cbe4e/topics/html/html.png

  - name: Javascript
    web_url: https://github.com/topics/javascript
    image_url: https://raw.githubusercontent.com/github/explore/9f270b9ddad21705ebd33f4602a0aec0d22cbe4e/topics/javascript/javascript.png

  - name: Material Design
    web_url: https://github.com/topics/material-design
    image_url: https://raw.githubusercontent.com/github/explore/9f270b9ddad21705ebd33f4602a0aec0d22cbe4e/topics/material-design/material-design.png

  - name: MongoDB
    web_url: https://github.com/topics/mongodb
    image_url: https://raw.githubusercontent.com/github/explore/9f270b9ddad21705ebd33f4602a0aec0d22cbe4e/topics/mongodb/mongodb.png
    
  - name: Node
    web_url: https://github.com/topics/node
    image_url: https://raw.githubusercontent.com/github/explore/9f270b9ddad21705ebd33f4602a0aec0d22cbe4e/topics/nodejs/nodejs.png

  - name: PostgreSQL
    web_url: https://github.com/topics/postgresql
    image_url: https://raw.githubusercontent.com/github/explore/9f270b9ddad21705ebd33f4602a0aec0d22cbe4e/topics/postgresql/postgresql.png

  - name: React Native
    web_url: https://github.com/topics/react-native
    image_url: https://raw.githubusercontent.com/github/explore/9f270b9ddad21705ebd33f4602a0aec0d22cbe4e/topics/react-native/react-native.png

  - name: Redux
    web_url: https://github.com/topics/redux
    image_url: https://raw.githubusercontent.com/github/explore/9f270b9ddad21705ebd33f4602a0aec0d22cbe4e/topics/redux/redux.png

  - name: Sass
    web_url: https://github.com/topics/sass
    image_url: https://raw.githubusercontent.com/github/explore/6c6508f34230f0ac0d49e847a326429eefbfc030/topics/sass/sass.png

  - name: Typescript
    web_url: https://github.com/topics/typescript
    image_url: https://raw.githubusercontent.com/github/explore/9f270b9ddad21705ebd33f4602a0aec0d22cbe4e/topics/typescript/typescript.png

  - name: Web Components
    web_url: https://github.com/topics/web-components
    image_url: https://raw.githubusercontent.com/github/explore/9f270b9ddad21705ebd33f4602a0aec0d22cbe4e/topics/web-components/web-components.png

  - name: Webpack
    web_url: https://github.com/topics/webpack
    image_url: https://raw.githubusercontent.com/github/explore/9f270b9ddad21705ebd33f4602a0aec0d22cbe4e/topics/webpack/webpack.png

certifications:
  - name: Google Mobile Sites
    web_url: https://github.com/topics/webpack
    image_url: https://upload.wikimedia.org/wikipedia/commons/thumb/5/53/Google_%22G%22_Logo.svg/1024px-Google_%22G%22_Logo.svg.png

  - name: Certified ScrumMaster (CSM)
    web_url: https://bcert.me/bc/html/show-badge.html?b=fincsanf
    image_url: https://bcert.me/bc/html/img/badges/generated/badge-7227.png